/* TTC Race Control — static GitHub Pages frontend.
   For multi-device live mode, set SUPABASE_URL and SUPABASE_ANON_KEY below,
   then run supabase.sql in your Supabase project. */
const SUPABASE_URL = window.TTC_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = window.TTC_SUPABASE_ANON_KEY || '';
const sb = SUPABASE_URL && SUPABASE_ANON_KEY ? supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY) : null;
const KEY='ttc-race-local-v1';
const baseRockRules=[
 ['progress_bonus','Progress Bonus',-2,'points'],['bonus_gate','Bonus Gate',-5,'points'],['reverse','Reverse / Backup',1,'points'],['gate_touch','Gate Marker Touch',10,'points'],['rollover','Rollover',5,'points'],['vehicle_touch','Vehicle Touch / Reposition',10,'points'],['direction_error','Course Direction Error',10,'points'],['winch','Use of Winch',3,'points'],['assisted_recovery','Assisted Recovery',10,'points'],['dns','Did Not Start (DNS)',50,'points']
];
const baseTimeRules=[['rollover','Rollover',20,'seconds'],['hand_of_god','Hand of God',40,'seconds'],['rig_touching','Rig Touching',40,'seconds'],['obstacle_skip','Obstacle Skip',60,'seconds'],['boundary','Boundary Hits',5,'seconds']];
let state=load(); let currentCourse=1; let timer={running:false,start:0,elapsed:0,interval:null};
function load(){return JSON.parse(localStorage.getItem(KEY)||'null')||{event:null,drivers:[],runs:[],rules:{rock:baseRockRules,time:baseTimeRules}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function $(id){return document.getElementById(id)}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function setScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function modeName(){return state.event?.mode==='time'?'TIME ATTACK CHALLENGE':'ROCK CRAWLING COMPETITION'}
function init(){
 document.querySelectorAll('.mode-card').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.event={...(state.event||{}),mode:b.dataset.mode};save()});
 $('createEventBtn').onclick=createEvent;$('addDriverBtn').onclick=addDriver;$('continueBtn').onclick=()=>{if(!state.drivers.length)return toast('Register at least one driver.');renderRace();setScreen('scoringScreen')};$('backSetupBtn').onclick=()=>setScreen('setupScreen');
 if(state.event){$('eventName').value=state.event.name||'';$('courseCount').value=state.event.courseCount||3;$('driverPanel').classList.remove('hidden');renderDrivers();document.querySelectorAll('.mode-card').forEach(x=>x.classList.toggle('selected',x.dataset.mode===state.event.mode))}
 updateConnection();
}
function updateConnection(){const b=$('connectionBadge');b.textContent=sb?'LIVE':'LOCAL';b.className='badge '+(sb?'online':'offline')}
function createEvent(){const name=$('eventName').value.trim();const count=+ $('courseCount').value;if(!name||count<1)return toast('Enter competition name and course count.');state.event={id:crypto.randomUUID(),name,courseCount:count,mode:document.querySelector('.mode-card.selected').dataset.mode,createdAt:new Date().toISOString()};state.drivers=[];state.runs=[];save();$('driverPanel').classList.remove('hidden');renderDrivers();toast('Competition created.')}
function addDriver(){if(!state.event)return toast('Create competition first.');const rig=$('rigNo').value.trim();const name=$('driverName').value.trim();const cat=$('category').value;const scale=$('scale').value;if(!rig||!name)return toast('Enter rig number and driver name.');if(state.drivers.some(d=>d.rig===rig))return toast('Rig number already registered.');state.drivers.push({id:crypto.randomUUID(),rig,name,category:cat,scale});save();['rigNo','driverName'].forEach(x=>$(x).value='');renderDrivers();syncDriver(state.drivers.at(-1));}
function renderDrivers(){const wrap=$('driverList');if(!state.drivers.length){wrap.innerHTML='<div class="status-note">No drivers registered yet.</div>';return}wrap.innerHTML=`<table class="data-table"><thead><tr><th>RIG</th><th>DRIVER</th><th>CLASS</th><th>SCALE</th><th></th></tr></thead><tbody>${state.drivers.map(d=>`<tr><td>${esc(d.rig)}</td><td>${esc(d.name)}</td><td>${d.category}</td><td>${d.scale}</td><td><button class="icon-btn" onclick="removeDriver('${d.id}')">REMOVE</button></td></tr>`).join('')}</tbody></table>`}
window.removeDriver=id=>{state.drivers=state.drivers.filter(d=>d.id!==id);state.runs=state.runs.filter(r=>r.driverId!==id);save();renderDrivers()}
function renderRace(){ $('raceTitle').textContent=state.event.name;$('raceModeLabel').textContent=modeName();$('courseTabs').innerHTML=Array.from({length:state.event.courseCount},(_,i)=>`<button class="course-tab ${i+1===currentCourse?'active':''}" onclick="selectCourse(${i+1})">COURSE ${i+1}</button>`).join('');$('currentCourseLabel').textContent=currentCourse;$('scoreDriver').innerHTML=state.drivers.map(d=>`<option value="${d.id}">#${esc(d.rig)} — ${esc(d.name)} (${d.category})</option>`).join('');$('scoreDriver').onchange=()=>{stopTimerForSwitch();renderScoreBoard();};renderScoreBoard();renderLeaderboard()}
window.selectCourse=n=>{stopTimerForSwitch();currentCourse=n;renderRace()}
function getRun(driverId,course){return state.runs.find(r=>r.driverId===driverId&&r.course===course)}
function renderScoreBoard(){const id=$('scoreDriver').value||state.drivers[0]?.id;if(!id){$('scoreBoard').innerHTML='';return}const existing=getRun(id,currentCourse);if(existing?.submitted){$('scoreBoard').innerHTML=runSubmitted(existing);return}const mode=state.event.mode;const rules=state.rules[mode];$('scoreBoard').innerHTML=`<div class="run-summary"><div class="metric"><span>${mode==='rock'?'POINTS':'RAW TIME'}</span><b id="metricMain">${mode==='rock'?existing?.points??0:fmtTime(existing?.elapsed??0)}</b></div><div class="metric"><span>${mode==='rock'?'TIME':'PENALTY TIME'}</span><b id="metricTime">${mode==='rock'?fmtTime(existing?.elapsed??0):`${existing?.penaltyTime??0}s`}</b></div><div class="metric"><span>PENALTIES</span><b id="metricCount">${existing?.events?.length??0}</b></div><div class="metric"><span>STATUS</span><b>${existing?'DRAFT':'READY'}</b></div></div>${timerHtml(existing)}<div class="score-grid">${rules.map(r=>`<button class="penalty-btn" onclick="applyRule('${r[0]}')">${esc(r[1])}<small>${r[2]>0?'+':''}${r[2]} ${r[3]}</small></button>`).join('')}</div><div class="submit-row"><button class="primary" onclick="submitRun()">CONFIRM / SUBMIT</button><button class="ghost" onclick="resetRun()">RESET</button></div><div class="status-note">Submitted scores are locked for this driver/course. No driver can be submitted twice for the same course.</div>`;updateTimerDisplay()}
function timerHtml(r){return `<div class="timer-label">COURSE TIMER</div><div id="timer" class="timer">${fmtTime(r?.elapsed??0)}</div><div class="timer-controls"><button class="timer-start" onclick="startTimer()">START</button><button onclick="pauseTimer()">PAUSE</button><button class="timer-finish" onclick="finishTimer()">FINISH</button><button onclick="resetTimer()">RESET TIME</button></div>`}
function ensureDraft(){const id=$('scoreDriver').value;let r=getRun(id,currentCourse);if(!r){r={id:crypto.randomUUID(),driverId:id,course:currentCourse,points:0,elapsed:0,penaltyTime:0,events:[],submitted:false};state.runs.push(r)}return r}
window.applyRule=key=>{const r=ensureDraft();const rule=state.rules[state.event.mode].find(x=>x[0]===key);if(!rule)return;r.events.push({key,label:rule[1],value:rule[2],unit:rule[3],at:new Date().toISOString()});if(state.event.mode==='rock')r.points+=rule[2];else r.penaltyTime+=rule[2];save();renderScoreBoard();renderLeaderboard();syncRun(r)}
window.submitRun=()=>{const r=ensureDraft();if(state.event.mode==='time'&&timer.running)finishTimer();r.submitted=true;r.submittedAt=new Date().toISOString();save();syncRun(r);renderScoreBoard();renderLeaderboard();toast('Score submitted.')}
window.resetRun=()=>{const id=$('scoreDriver').value;state.runs=state.runs.filter(r=>!(r.driverId===id&&r.course===currentCourse));save();resetTimer();renderScoreBoard();renderLeaderboard()}
function startTimer(){const r=ensureDraft();if(r.submitted)return toast('This score is already submitted.');if(timer.running)return;timer.running=true;timer.start=Date.now()-(r.elapsed||0);const el=$('timer');if(el)el.classList.add('running');timer.interval=setInterval(()=>{r.elapsed=Date.now()-timer.start;updateTimerDisplay();if(Math.floor(r.elapsed/1000)%2===0)save()},100)}
function pauseTimer(){if(!timer.running)return;const r=ensureDraft();r.elapsed=Date.now()-timer.start;timer.running=false;clearInterval(timer.interval);timer.interval=null;save();updateTimerDisplay();syncRun(r);const el=$('timer');if(el)el.classList.remove('running')}
function finishTimer(){if(timer.running)pauseTimer();const r=ensureDraft();save();syncRun(r);toast('Timer finished. Review before submitting.')}
function resetTimer(){timer.running=false;clearInterval(timer.interval);timer={running:false,start:0,elapsed:0,interval:null};const el=$('timer');if(el){el.textContent='00:00.00';el.classList.remove('running')}}
function stopTimerForSwitch(){if(!timer.running)return;const id=$('scoreDriver')?.value;const r=id?getRun(id,currentCourse):null;if(r){r.elapsed=Date.now()-timer.start;save();syncRun(r)};timer.running=false;clearInterval(timer.interval);timer.interval=null;timer.start=0}
function updateTimerDisplay(){const r=state.event?.mode==='time'?getRun($('scoreDriver')?.value,currentCourse):null;const el=$('timer');if(el)el.textContent=fmtTime(r?.elapsed||0);const m=$('metricMain');if(m)m.textContent=state.event.mode==='rock'?(r?.points??0):fmtTime(r?.elapsed||0);const t=$('metricTime');if(t)t.textContent=state.event.mode==='rock'?fmtTime(r?.elapsed||0):`${r?.penaltyTime??0}s`;const c=$('metricCount');if(c)c.textContent=r?.events?.length??0}
function runSubmitted(r){return `<div class="run-summary"><div class="metric"><span>STATUS</span><b>SUBMITTED</b></div><div class="metric"><span>${state.event.mode==='rock'?'POINTS':'RAW TIME'}</span><b>${state.event.mode==='rock'?r.points:fmtTime(r.elapsed)}</b></div><div class="metric"><span>${state.event.mode==='rock'?'TIME':'PENALTY TIME'}</span><b>${state.event.mode==='rock'?fmtTime(r.elapsed):r.penaltyTime+'s'}</b></div><div class="metric"><span>EVENTS</span><b>${r.events.length}</b></div></div><div class="status-note">This driver/course score is locked. Move to another course to continue.</div>`}
function renderLeaderboard(){const rows=state.drivers.map(d=>{const rr=state.runs.filter(r=>r.driverId===d.id&&r.submitted);const totalPoints=rr.reduce((a,r)=>a+r.points,0);const totalRaw=rr.reduce((a,r)=>a+r.elapsed,0);const totalPenalty=rr.reduce((a,r)=>a+r.penaltyTime,0);const totalTime=totalRaw+totalPenalty*1000;return{d,rr,totalPoints,totalRaw,totalPenalty,totalTime}});rows.sort((a,b)=>state.event.mode==='rock'?(a.totalPoints-b.totalPoints)||(a.totalRaw-b.totalRaw):(a.totalTime-b.totalTime));$('leaderboard').innerHTML=`<table class="leader-table"><thead><tr><th>RANK</th><th>DRIVER</th><th>C1</th><th>C2</th><th>C3</th><th>TOTAL</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td class="rank">${i+1}</td><td>#${esc(x.d.rig)} ${esc(x.d.name)}</td>${[1,2,3].map(c=>{const r=x.rr.find(z=>z.course===c);return `<td>${r?(state.event.mode==='rock'?r.points:fmtTime(r.elapsed+r.penaltyTime*1000)):'—'}</td>`}).join('')}<td><b>${state.event.mode==='rock'?x.totalPoints:fmtTime(x.totalTime)}</b></td></tr>`).join('')}</tbody></table><div class="status-note">Rock crawling: lowest cumulative points wins; cumulative time breaks ties. Time attack: fastest cumulative adjusted time wins. Results remain provisional until all courses are completed.</div>`}
function fmtTime(ms){const s=Math.max(0,Math.floor(ms/1000));const m=Math.floor(s/60);const sec=s%60;const cs=Math.floor((ms%1000)/10);return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${String(cs).padStart(2,'0')}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function syncDriver(d){if(!sb||!state.event)return;await sb.from('drivers').upsert({id:d.id,event_id:state.event.id,rig_number:d.rig,driver_name:d.name,category:d.category,scale:d.scale})}
async function syncRun(r){if(!sb||!state.event)return;await sb.from('runs').upsert({id:r.id,event_id:state.event.id,driver_id:r.driverId,course_no:r.course,points:r.points,elapsed_ms:r.elapsed,penalty_time_seconds:r.penaltyTime,events:r.events,submitted:r.submitted,mode:state.event.mode})}
if(sb){sb.channel('ttc-live').on('postgres_changes',{event:'*',schema:'public',table:'runs'},payload=>{const r=payload.new;if(!r||r.event_id!==state.event?.id)return;const local=getRun(r.driver_id,r.course);if(local){Object.assign(local,{points:r.points,elapsed:r.elapsed_ms,penaltyTime:r.penalty_time_seconds,events:r.events||[],submitted:r.submitted})}else state.runs.push({id:r.id,driverId:r.driver_id,course:r.course,points:r.points,elapsed:r.elapsed_ms,penaltyTime:r.penalty_time_seconds,events:r.events||[],submitted:r.submitted});save();renderLeaderboard();renderScoreBoard()}).subscribe()}
init();
